// Configuration file - Auto-generated by GitHub Actions
// DO NOT edit this file directly in production - use environment variables instead
const CONFIG = {
    "MAPBOX_ACCESS_TOKEN": "pk.eyJ1Ijoib25saW5lZmNoZW4iLCJhIjoiY21hdnZ1eHY5MDZ2eDJsczVrZXZqZHQ2YyJ9.7weQB5Uz0oPDIhlWC79FiA",
    "TIMEZONE": {
        "offset": 8,
        "name": "Asia/Shanghai"
    },
    "SIGNATURE": {
        "line1": "\u6562\u95ee\u8def\u5728\u4f55\u65b9\uff0c\u8def\u5728\u811a\u4e0b",
        "line2": ""
    },
    "NAVIGATION_LINKS": {
        "summary": {
            "title": "Summary",
            "url": "summary.html",
            "target": "_self"
        },
        "blog": {
            "title": "Blog",
            "url": "https://your-blog.com",
            "target": "_blank"
        },
        "about": {
            "title": "About",
            "url": "https://your-about-page.com",
            "target": "_blank"
        }
    }
};