name: Sync Strava Data and Deploy

on:
  # Run every 8 hours
  schedule:
    - cron: '0 */8 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      full_sync:
        description: 'Perform full sync (fetch all activities)'
        required: false
        default: 'false'
        type: boolean

  # Run on push to main branch
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Sync Strava data
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        FULL_SYNC: ${{ github.event.inputs.full_sync || 'false' }}
      run: |
        python sync_strava_data.py
    
    - name: Generate config.js with Mapbox token
      env:
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      run: |
        # Generate config.js from template
        python generate_config.py
    
    - name: Generate statistics and visualizations
      run: |
        python calculate_stats.py
        python generate_visualizations.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          git add data/activities.json generated/ config.js
          git commit -m "Auto-update: Sync Strava data and regenerate visualizations $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
          echo "DATA_UPDATED=true" >> $GITHUB_ENV
        else
          echo "No changes detected"
          echo "DATA_UPDATED=false" >> $GITHUB_ENV
        fi
    
    - name: Setup Pages
      if: env.DATA_UPDATED == 'true' || github.event_name == 'push'
      uses: actions/configure-pages@v4
    
    - name: Upload to GitHub Pages
      if: env.DATA_UPDATED == 'true' || github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        name: pages-artifact
        path: .
    
    - name: Deploy to GitHub Pages
      if: env.DATA_UPDATED == 'true' || github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: pages-artifact